### ISSUE TITLE
Recipe for Vuejs.org Cookbook?

### ISSUE THREAD

**Issue by sdras** [team-innovation/vue-sfc-rollup#1]
Hi! 👋
I loved your lightning talk about creating an SFC that you can share- would you be interested in creating a Cookbook Recipe? I think the community would really benefit from it.

Thanks!

**Comment by mgdodge** [comment]
@sdras, I'd be happy to! There's obviously a bit of work to do here since I threw the whole thing together last minute, but my intent was to create something that I could give back to the community, so I'll get this repo in shape!

Is there anywhere I should look for recipe guidelines?

**Comment by sdras** [comment]
Yep, all of the guidelines are right on the index page: [https://vuejs.org/v2/cookbook/](https://vuejs.org/v2/cookbook/). You can also read a couple of recipes to kind of get the feel of the flow. Thanks!

**Comment by mgdodge** [comment]
Closing, recipe submitted for approval: https://github.com/vuejs/vuejs.org/pull/1558
