### ISSUE TITLE
Request: Contributing to the Vue Docs

### ISSUE THREAD

**Issue by bencodezen** [team-innovation/vue-sfc-rollup#100]
Hey team! 

My name is Ben Hong and I'm on the Vue core team. Love the work that you've done here. I'd love to chat with you about helping to contribute to the official Vue docs. If this is something you'd be interested in, would love to touch base and talk about more details!

**Comment by mgdodge** [comment]
Happy to get more details. PM me and we can talk. Depending on the contributions, might be better to go through my personal account rather than this one, which is tied to Vivint and thus is subject to their review/release process.

**Comment by mgdodge** [comment]
The decision has been made to deprecate `vue-sfc-rollup` in favor of better tooling in the Vue ecosyste, specifically the [vite "library build"](https://vitejs.dev/guide/build.html#library-mode) configuration. It is an excellent project, which is capable of everything vue-sfc-rollup strived to accomplish, and more.
