### ISSUE TITLE
Vuetify Support

### ISSUE THREAD

**Issue by projectec2020** [team-innovation/vue-sfc-rollup#106]
Need Vuetify support

**Comment by mgdodge** [comment]
As I indicated [in earlier requests](https://github.com/team-innovation/vue-sfc-rollup/issues/44), I will not be adding support for specific third party libraries to this minimal utility. There are numerous examples to be found on how to leverage third-party libraries like Vuetify. [rollup-plugin-vuetify](https://www.npmjs.com/package/rollup-plugin-vuetify) might be a good place to start, it contains [sample rollup configuration](https://github.com/vatson/rollup-plugin-vuetify/blob/8c685f5eb0954a73b61d0ef338bbb29e1df453f8/demo/rollup.js#L20) that you could combine with the output of this tool to get things started. The key is to use rollup `externals` configuration to prevent rollup from including a separate copy of vuetify in the build.
