### ISSUE TITLE
`sfc-init` generated configuration with unused external imports

### ISSUE THREAD

**Issue by DerYeger** [team-innovation/vue-sfc-rollup#109]
I recently created a project with `sfc-init`.

When building the project, the warning

```
(!) Unused external imports
withScopeId imported from external module "vue" but never used in "src\masonry-wall.vue?vue&type=template&id=257b3451&lang.js" and "src\masonry-wall.vue?vue&type=script&lang.ts"
```

is printed for every build format.

The configuration can be found at https://github.com/DerYeger/vue-masonry-wall/blob/master/build/rollup.config.js.

**Comment by DerYeger** [comment]
Seems like the warning is caused by adding

```vue
<style scoped>
/* Some style */
</style>
```

to the SFC.

**Comment by mgdodge** [comment]
Is this still an issue? I checked out your repo and ran a build, never saw the issue. It's likely upstream anyway, since none of the code coming from `sfc-init` directly uses `withScopeId` as reported, so it's likely something upstream...

**Comment by DerYeger** [comment]
> Is this still an issue? I checked out your repo and ran a build, never saw the issue. It's likely upstream anyway, since none of the code coming from `sfc-init` directly uses `withScopeId` as reported, so it's likely something upstream...

I removed all `<style scoped>` occurrences, which fixed the issue. I agree that it is most likely an upstream issue after finding the cause.
