### ISSUE TITLE
How To / Feature Request: vuex store

### ISSUE THREAD

**Issue by SumNeuron** [team-innovation/vue-sfc-rollup#11]
If one is seeking to publish a multi-sfc library, then it could be the case that their application could or does benefit from a vuex store - especially if the components are vertically integrated. 

Vuex already supports a module structure.
So what would be needed to make it possible to have a store with these components?

- write the store as a module
- have the components, which rely on the store, take (as a prop) the store's module name
- on created initialize the store module if it doesnt exist

While this doesnt seem to have any thing to do with this sfc-rollup, I can not quite nail the convention for dynamically having rolluped sfcs do step 3. So added this to the cookbook would be cool :)

unless you have a better way of doing this :D

**Comment by mgdodge** [comment]
As you stated, this doesn't seem to have anything to do with vue-sfc-rollup, so I am closing as wontfix - it's out of the scope of this utility. The idea you are suggesting seems similar to [this one](https://alligator.io/vuejs/vuex-dynamic-modules/), perhaps that will accomplish what you need. Of course, it's up to you to inform users of your library of the vuex dependency.
