### ISSUE TITLE
Using vue-sfc in Angular App

### ISSUE THREAD

**Issue by mrfy** [team-innovation/vue-sfc-rollup#112]
Hi,

is it possible to use vue single file component, which was build using `vue-sfc-rollup` package and shared by npm packagage, with Angular app?

**Comment by mgdodge** [comment]
vue-sfc-rollup doesn't create 'web components' that can be used separately from vue. However, if you have a hybrid app that uses both both Vue and Angular, there is no reason I can see why components built this way would cause problems. It's definitely not something I'm going to be able to help you with, or document in any way.
