### ISSUE TITLE
jest unit testing support

### ISSUE THREAD

**Issue by speedyankur** [team-innovation/vue-sfc-rollup#115]
Any idea, how we can easily add `vue-cli-service test:unit` support?
I tried adding 
`npm install --save-dev @vue/cli-plugin-unit-jest`
but while runnig 
`vue-cli-service test:unit`
It gave me an error
`Error: Could not resolve a module for a custom reporter.
  Module name: jest-junit`

**Comment by mgdodge** [comment]
The decision has been made to deprecate `vue-sfc-rollup` in favor of better tooling in the Vue ecosyste, specifically the [vite "library build"](https://vitejs.dev/guide/build.html#library-mode) configuration. It is an excellent project, which is capable of everything vue-sfc-rollup strived to accomplish, and more.
