### ISSUE TITLE
Build problems when upgrading vue & @vue/compiler-sfc for using <script setup> along with scoped scss

### ISSUE THREAD

**Issue by TJCollin** [team-innovation/vue-sfc-rollup#116]
## repo
https://github.com/TJCollin/vue-sfc-demo

## vue & vue complier version
"@vue/compiler-sfc": "^3.2.20"

"vue": "^3.2.20"

## step 1
init project: `npx init vue-sfc-rollup`
upgrade vue: `yarn add vue@next @vue/compiler-sfc sass-loader@10.2.0 sass`

## step2
create `src/lib-components/a.vue` `src/lib-components/b.vue` 
change the entry in `src/lib-components/index.ts`

## step3
run `yarn build`

## error message
`semantic error TS6133: '_withScopeId' is declared but its value is never read.`

## more
However if i remove the `scoped` in style of `b.vue`, it works fine.

both `a.vue` & `b.vue` works fine with `yarn serve`.

could you please help me with this? 

thanks a lot .

**Comment by peshanghiwa** [comment]
Having the exact same issue...

**Comment by mgdodge** [comment]
The decision has been made to deprecate `vue-sfc-rollup` in favor of better tooling in the Vue ecosyste, specifically the [vite "library build"](https://vitejs.dev/guide/build.html#library-mode) configuration. It is an excellent project, which is capable of everything vue-sfc-rollup strived to accomplish, and more.
