### ISSUE TITLE
Component not working weel when importing in another project

### ISSUE THREAD

**Issue by jdflaugergues** [team-innovation/vue-sfc-rollup#117]
Hi,

I'm trying to use vue-sfc-rollup to build my own vuejs 3 library component with typescript but I've some issues.
I have created a simple component with an input and a validation (with vee-validate), I build my project library and imported it in my main Vuejs web app project, but it doesn't work well.

Indeed, events with watchEffect are not emmited to parent component and validation from vee-validate not working.
If I use exactly the same component in my own project it works, this is why I think there is a issue during the building project.

I have tried the composant with and without script setup but I have got the same error.
Here is the source of my project : https://github.com/jdflaugergues/vue-lib

[Package.json](https://github.com/jdflaugergues/vue-lib/blob/master/package.json) 
[Rollup Config](https://github.com/jdflaugergues/vue-lib/blob/master/build/rollup.config.js)
[The component](https://github.com/jdflaugergues/vue-lib/blob/master/src/lib-components/TextField/TextField.vue)

Thanks for your help.

**Comment by mgdodge** [comment]
The decision has been made to deprecate `vue-sfc-rollup` in favor of better tooling in the Vue ecosyste, specifically the [vite "library build"](https://vitejs.dev/guide/build.html#library-mode) configuration. It is an excellent project, which is capable of everything vue-sfc-rollup strived to accomplish, and more.
