### ISSUE TITLE
using quasar component in a library not rendering

### ISSUE THREAD

**Issue by wpplumber** [team-innovation/vue-sfc-rollup#120]
Thank yo for this simple Vue 2 / Vue 3 library starter kit.

I used the v3 in project but  returns unexpected output 

`<q-btn label="quasar" class="q-mr-sm"></q-btn>`

register.js in quasar /boot 
```
import { boot } from 'quasar/wrappers'
import Geoq from '../../../dist/geoq.esm' // ui already defined in quasar.conf.js

export default boot(async ({ app }) => {
  app.use(Geoq)
})
```

**Comment by mgdodge** [comment]
The decision has been made to deprecate `vue-sfc-rollup` in favor of better tooling in the Vue ecosyste, specifically the [vite "library build"](https://vitejs.dev/guide/build.html#library-mode) configuration. It is an excellent project, which is capable of everything vue-sfc-rollup strived to accomplish, and more.
