### ISSUE TITLE
CSS files are not building when specfied on `entry.ts` (tailwind generated css)

### ISSUE THREAD

**Issue by anburocky3** [team-innovation/vue-sfc-rollup#122]
Have transpilled tailwind CSS to normal traditional CSS and while importing on the `entry.js` while, building, it is not included in the `dist` folder

**Comment by mgdodge** [comment]
The decision has been made to deprecate `vue-sfc-rollup` in favor of better tooling in the Vue ecosyste, specifically the [vite "library build"](https://vitejs.dev/guide/build.html#library-mode) configuration. It is an excellent project, which is capable of everything vue-sfc-rollup strived to accomplish, and more.
