### ISSUE TITLE
Different name and savePath

### ISSUE THREAD

**Issue by TrayHard** [team-innovation/vue-sfc-rollup#131]
For some reason when i use cli arguments I'm not able to define the savepath and package name apart from each other, which is very confusing because i want path to be "./lib" but the name should be not just "lib", and i can do that with answering the questions but for some reason in the code (https://github.com/team-innovation/vue-sfc-rollup/blob/e10fca2d7b0706da27e64826f315621fd2b98696/sfc-init.js) it's written to define savePath the same as npmName which limits your freedom of naming everything how you want it to be. 

Could you please separate npmName and savePath?

**Comment by mgdodge** [comment]
The decision has been made to deprecate `vue-sfc-rollup` in favor of better tooling in the Vue ecosyste, specifically the [vite "library build"](https://vitejs.dev/guide/build.html#library-mode) configuration. It is an excellent project, which is capable of everything vue-sfc-rollup strived to accomplish, and more.
