### ISSUE TITLE
Can't import global SCSS variables

### ISSUE THREAD

**Issue by splurtcake** [team-innovation/vue-sfc-rollup#134]
Hi all,

I've searched high and low for a solution to this and can't get anything to work. Hopefully someone can point me in the right direction.

```
// MyComponent.vue
<template>
  <div class="test" />
</template>
<style type="scss">
  .test {
    color: $primary;
  }
</style>
```

```
// vue.config.js
...
loaderOptions: {
  css: {
      esModule: false
  },
  sass: {
      prependData: '@use "sass:math";@import "src/assets/styles/variables.scss";@import "src/assets/styles/mixins.scss";'
  }
}
...
```

```
// rollup.config.js
vue: {
  css: false,
  preprocessStyles: true,
  preprocessOptions: {
    scss: vueConfig.css.loaderOptions.sass,
  },
},
```

When running the rollup build I get the following errors
```
src/Test/Test.vue?vue&type=style&index=0&id=3c54bc06&lang.css
Error: Undefined variable.
   ╷
6 │         color: $primary;
   │                       ^^^^^^^^^^
   ```

**Comment by mgdodge** [comment]
The decision has been made to deprecate `vue-sfc-rollup` in favor of better tooling in the Vue ecosyste, specifically the [vite "library build"](https://vitejs.dev/guide/build.html#library-mode) configuration. It is an excellent project, which is capable of everything vue-sfc-rollup strived to accomplish, and more.
