### ISSUE TITLE
This package has been deprecated [New: `Vue SFC Vite`]

### ISSUE THREAD

**Issue by AfzalSabbir** [team-innovation/vue-sfc-rollup#138]
# Author message:
vue-sfc-rollup is now considered deprecated. The recommended replacement is vite, specifically the "library build" configuration.

# Alternative:
Try [vue-sfc-vite](https://www.npmjs.com/package/vue-sfc-vite).

## [Vue SFC Vite](https://www.npmjs.com/package/vue-sfc-vite) - A Vue 3 SFC Vite template

> A package to create Vue 3 SFC Vite projects.
<sub><sup>Inspired by [VueSFCRollup](https://github.com/team-innovation/vue-sfc-rollup)</sup></sub>
**VueSFCRollup** was a great package to create SFC Rollup projects. But after there deprecation of the package, we decided to create a similar package for Vite.
> Used [`Vite`](https://vitejs.dev/)/[`Library Mode`](https://vitejs.dev/guide/build.html#library-mode) configuration to create a single file component template for Vue 3 _(Supports Vue 2 as well)_.
> [`vue-sfc-vite`](https://www.npmjs.com/package/vue-sfc-vite) is a CLI templating utility that scaffolds a minimal setup for compiling a Vue Single File Component (SFC) - into a form ready to share via npm. It doesn't assume any particular flavor of CSS or docs generator, so you can use what you're already used to. It's the fastest way to produce npm-ready vue components!

**Comment by wobsoriano** [comment]
Also, if anyone's interested in a bundle-less component library starter

https://github.com/wobsoriano/vue-sfc-unbuild
