### ISSUE TITLE
vueRuntimeHelpers is not defined error 

### ISSUE THREAD

**Issue by akshayashet** [team-innovation/vue-sfc-rollup#25]
Hi,

I have tried create simple test component lib using vue-sfc-rollup CLI. 

Build created successfully three files.
![image](https://user-images.githubusercontent.com/3539011/67923387-b54e7580-fbd3-11e9-812d-2fcaa980786b.png)

When I use minified version in html file getting error 

> vueRuntimeHelpers is not defined

![image](https://user-images.githubusercontent.com/3539011/67923438-d7e08e80-fbd3-11e9-9885-ff14b74f0f91.png)

![image](https://user-images.githubusercontent.com/3539011/67923272-5c7edd00-fbd3-11e9-8f9c-296e3bd12bec.png)

Please help me to fix this. 

I have uploaded code here.
https://github.com/akshayashet/nps-survey-sample

Thanks

**Comment by akshayashet** [comment]
I have updated the rollup-plugin-vue version to 5.1.1

Still  component not rendering.
![image](https://user-images.githubusercontent.com/3539011/67971014-042af800-fc32-11e9-84b3-e5b66b023caa.png)

Update git repo:
https://github.com/akshayashet/nps-survey-sample

**Comment by mgdodge** [comment]
The only problem now is that your html is loading vue and the component, but you aren't mounting it anywhere. Here is the correct html:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <script src="https://unpkg.com/vue"></script>
    <script src="nps-survey.min.js"></script>
  </head>
  <body>
    <div id="app">
      <h1>Test lib</h1>
      <nps-survey></nps-survey>
    </div>
    <script>new Vue({ el: '#app' });</script>
  </body>
</html>
```

**Comment by mgdodge** [comment]
Fixed vueRuntimeHelpers bug via updated dependencies in df25bc5
