### ISSUE TITLE
Bundling with a third-party package that also import Vue. (i.e. aliasing Vue)

### ISSUE THREAD

**Issue by LeCoupa** [team-innovation/vue-sfc-rollup#26]
I am struggling since yesterday night [about this issue](https://github.com/logaretm/vee-validate/issues/2471). It seems like something widespread, but I can't figure out how to make it work in my `rollup.config.js` file.

```
[Vue warn]: $listeners is read-only.
```

> The $attrs, $listeners, and other warnings are displayed if there's more than one instance of Vue loaded.

I am importing two components from VeeValidate (that also use Vue), so I am trying to alias it.

```
import { ValidationObserver, ValidationProvider } from "vee-validate";
```

Here is my base config variable ([you can find the full configuration file here](https://github.com/LeCoupa/vuedarkmode/blob/vee-validate/build/rollup.config.js))

```

const baseConfig = {
  input: "src/entry.js",
  plugins: {
    preVue: [
      alias({
        entries: {
          vue: "vue/dist/vue.esm"
        }
      }),
      replace({
        "process.env.NODE_ENV": JSON.stringify("production")
      }),
      commonjs()
    ],
    vue: {
      css: true,
      template: {
        isProduction: true
      }
    },
    postVue: [buble()]
  }
};
```

Unfortunately, It does not solve anything. How can we bundle third-party packages that also import Vue in a library? How do you deal with this issue in your component libraries?

**Comment by mgdodge** [comment]
Could you provide a little more information:

- Does the error about `$listeners` appear during build, or in browser?
- Can you provide a sample of the code that is generating the error? Perhaps a sample SPA or HTML file (if it occurs when using in the browser without SPA build process...)

I checked out the 'vee-validate' branch of your dark mode repo, and ran a build. I got no such error during build.

In general, if there are dependencies on third party libraries, they should be listed in the rollup `external` list at a minimum, possibly in the `globals` list if they expose globals for UMD/IIFE usage. It seems you are doing that with vee-validate, so there should not be any issues. You also should have no need for aliasing Vue if you are not importing it directly yourself. When third party libraries are listed in `external` and `globals` they are not included in your bundle, so there is still no need aliasing.

If there are multiple versions of Vue being loaded, as some of the linked issues seem to indicate, that should be easier to spot with example code.

**Comment by mgdodge** [comment]
I am closing this issue, as it is a rollup configuration issue beyond the _minimal_ configuration vue-sfc-rollup is designed to create. Without additional information/sample code, it's difficult to give additional advice or even reproduce the issue.

**Comment by luckylooke** [comment]
For anyone landing here, maybe it can help you.
I have added:
```js
    resolve: {
      alias: {
        // fixes $attrs/$listeners errors
        vue: path.resolve("./node_modules/vue")
      }
    }
```
into my application (understand library consumer) webpack config
and it solves this issue
happy coding 👍

**Comment by juuuuuuuuuuuuuu** [comment]
@luckylooke 
what is difference "vue/dist/vue.esm" and path.resolve("./node_modules/vue") ??
i don't know..
