### ISSUE TITLE
Add '@/' alias as a default

### ISSUE THREAD

**Issue by johannes-z** [team-innovation/vue-sfc-rollup#27]
In vue cli you can use `@/components/...` out of the box.  `@` is aliasing the `./src/` folder. This should be a default, otherwise you'd have to adjust the rollup config for this.

**Comment by mgdodge** [comment]
If you want to submit a pull request, this would be great! If not, I will make the change - though it might be delayed a bit.

**Comment by johannes-z** [comment]
Sadly I don't have a lot of experience with rollup and in my experiments couldn't figure out how to make it work with `.vue` files.

**Comment by mgdodge** [comment]
Just pushed v2.1.0 which adds this capability. Thanks for the suggestion!
