### ISSUE TITLE
[Feature Request] Create library with Typescript

### ISSUE THREAD

**Issue by joaoeudes7** [team-innovation/vue-sfc-rollup#29]
Hello, 
Good job in this tool!

It would be interesting to add settings to the typescript option when selecting, this tool would make it much easier to rollup settings for Vue with Typescript plugins.

**Comment by mgdodge** [comment]
I've been thinking about this, actually. Not too much of a stretch. If you want to submit a PR, I'm happy to give you credit. Otherwise, it's something I can probably work on through the holiday.

**Comment by mgdodge** [comment]
This has been added, now in v2.2.0. Thanks for the suggestion!
