### ISSUE TITLE
After install, sfc-init has require error

### ISSUE THREAD

**Issue by raublekick** [team-innovation/vue-sfc-rollup#30]
C:\Users\jaraub\Workspace>sfc-init

Error: Cannot find module './lib/helpers'
Require stack:
- C:\Users\jaraub\AppData\Roaming\npm\node_modules\vue-sfc-rollup\sfc-init.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:690:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:852:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at Object.<anonymous> (C:\Users\jaraub\AppData\Roaming\npm\node_modules\[4mvue-sfc-rollup[24m\sfc-init.js:8:17)
[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:815:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\jaraub\\AppData\\Roaming\\npm\\node_modules\\vue-sfc-rollup\\sfc-init.js'[39m
  ]
}

**Comment by mgdodge** [comment]
Thanks! Left out a line in package.json, just pushed v2.2.1 to resolve this.
