### ISSUE TITLE
Error when importing components into the main component 

### ISSUE THREAD

**Issue by rtransat** [team-innovation/vue-sfc-rollup#31]
Hi!

I have this code:

components/index.js
```
/* eslint-disable import/prefer-default-export */
export { default as Hue } from './MyComponent/MyComponent.vue';
```

components/MyComponent/MyComponent.vue
```
<script>
import * as icons from "../Icon";
...
</script>
```

components/Icon/index.js
```
import Attic from "./Room/Attic";
import Balcony from "./Room/Balcony";

export default {
  Attic,
  Balcony,
}
```

The build error is: `Error: Could not resolve './Room/Balcony' from src\components\Icon\index.js`

How to use other component and build them into the final build?
The `npm run serve` works great but I don't know how to fix the path for the build.

Regards

**Comment by mgdodge** [comment]
The above code would work if you have the following structure:
```
src/components/index.js
src/components/MyComponent/MyComponent.vue
src/components/Icon/index.js
src/components/Icon/Room/Attic.js
src/components/Icon/Room/Balcony.js
```
If the `Room` folder isn't inside the `Icon` directory, you need to check your import paths. If you end up seeing a lot of `../` type of stuff, you can define aliases in the rollup.config.js file (the `@` to `src` alias is already defined there)

**Comment by rtransat** [comment]
Thx! My issue was `import Attic from "./Room/Attic";` instead of `import Attic from "./Room/Attic.vue";`

By the way, it's possible to configure the build process to accept `import Attic from "./Room/Attic";` as a vue file?

**Comment by mgdodge** [comment]
It is possible, but not in rollup core. See their explanation [here](https://github.com/rollup/rollup/issues/1052) as well as possible solutions.
