### ISSUE TITLE
How to use the packaged component in another project?

### ISSUE THREAD

**Issue by findingorder** [team-innovation/vue-sfc-rollup#37]
Hello,
I am able to package the component just as the docs say to do.  Then when I copy the .min.js file into another project and attempt to use the component, I always get the error:
```
Vue warn handler:  Failed to mount component: template or render function not defined.
```
The way I'm trying to use the component from inside another Vue component is this:
```js
import Vue from 'vue'
import MyComponent from '../lib/my-components.min.js'
Vue.use(MyComponent)
```
Then in the components section:
```js
components: {
    'my-component': MyComponent
}
```
Then in the template:
```html
<my-component></my-component>
```
What am I missing here? What is the correct way to use the component in another project?
Thanks,
Phil

**Comment by mgdodge** [comment]
vue-sfc-rollup prepares components to upload to npm - are you publishing it there? If so, there is no need to copy files around, you can just install it via npm and use it like any other npm package.

If you aren't uploading it to npm, then the `.min.js` file you copied is the one meant to be used via `<script>` tag directly - and your example here is using it as a module. So you need the `.esm.js` verision instead.

Honestly, you should't just copy the files around, it kind of defeats the purpose of this utility. You should publish it to npm, even if left private. That way, you can keep all your projects up to date a lot easier, and all of this is resolved for you automatically.

**Comment by ngmiduc** [comment]
I actually have the same problem.
(1) I can not use import statements but with require I can import the module into another project
(2) When using it in the template - I get the same warning with

`Vue warn handler:  Failed to mount component: template or render function not defined.`

Is that an issue to using new Vue3.0beta?
