### ISSUE TITLE
how correctly install plugin to same vue instance as main app?

### ISSUE THREAD

**Issue by ahoyahoy** [team-innovation/vue-sfc-rollup#43]
https://stackoverflow.com/questions/62012207/how-to-install-vue-addon-with-same-vue-instance-as-main-app

**Comment by mgdodge** [comment]
The auto-install code that is surrounded by the ES_BUILD check:
```js
if ('false' === process.env.ES_BUILD) {
...
}
```
is intended to allow the build process to remove the code from the final output for commonjs and script tag (ssr and iife) versions. Running `npm run build` should do this for you. If you are seeing this code in the final output, the build process is not working properly.

When using the component in another project with a build process, `Vue.use()` is how you would load the component globally. You can also load it as part of the `components` property of another component, if it is only used in a specific section of your code.

When using it in a browser directly or in an SSR capacity, the auto-install would take care of things if the script was loaded after Vue itself was.

Feel free to post a link to a github repo or some other location containing the component you are developing if you still have issues. That way someone else can download the code, run the build, and verify that the build process is producing the appropriate output.

**Comment by mgdodge** [comment]
@ahoyahoy Have you made any progress on this, or do you have a link to sample code?

**Comment by mgdodge** [comment]
Just had a thought as I was releasing v4.0.0-beta.0 which might address this.

Prior versions of the install function would track whether or not the component had been installed or not. It was based on some older code, and Vue tracks that anyway. If you had multiple instances of Vue, and the component module is treated as a singleton, then it's possible the install function would work in the first instance, but not in the second.

If you could try v4.0.0-beta.0 and see if that resolves things, or just remove the following from your existing install function, it might be worth a try:

```js
// Remove the following lines
if (install.installed) return;
install.installed = true;
```
