### ISSUE TITLE
Create an examples route

### ISSUE THREAD

**Issue by JordashTalon** [team-innovation/vue-sfc-rollup#48]
I'm curious how to create an examples route?

ex: http://localhost:8080/examples

So I can quickly test the component with different parameters?

Love this repo BTW super helpful.

**Comment by mgdodge** [comment]
This issue doesn't include enough information to even begin addressing. Anything to do with specific dev configuration/examples is outside the scope of this repo - vue-sfc-rollup is concerned with minimal scaffolding and compilation setup. It will create the files necessary to start using the vue cli, which is the recommended method of working with Vue. Configuring that dev experience further is left up to the user.
