### ISSUE TITLE
How to externalilze dependency and Use component with it

### ISSUE THREAD

**Issue by Lahori-Jawan** [team-innovation/vue-sfc-rollup#5]
Hey there. You rock! Every thing worked just as is mentioned in README and actually I followed the instructions in cmd and Bam!!! 

So now that I have 3 files i.e. `.esm`, `.min`, `.umd` , I wasn't sure which one to use and how so I simply replaced one with other and found that `file.esm.js`  had some reasonable errors i.e. 
```Error in mounted hook: "ReferenceError: noUiSlider is not defined" found in ---> <VSlider>```
and I imported that `nouislider` inside `App.vue'` file but still error but then I used it inside the generated `.esm.js` file, it works great.

So my question is how to make it compatible with 3rd party plugin so that I don't have to include it in my plugin and publish?

**Comment by mgdodge** [comment]
As a first step, take a look at the companion article for this utility found in the official vue cookbook: https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html.

Depending on your use case, the files you create can be used several ways, and the way they relate to other components can vary a little with each.

Also, if you are sure you have loaded your component's dependencies purposely but are still getting errors, the dependency might need to be registered via Vue.use(...) to make it available for use. Not all components auto-register like those packaged with this utility.

**Comment by Lahori-Jawan** [comment]
@mgdodge I have published the [vue component](https://www.npmjs.com/package/veeno) to npm, thanks to you and everything is working great in the node environment. but I can't use it in browser via unpkg. 

I have gone through this [discussion](https://github.com/vuejs/vuejs.org/pull/1558) where you mention that [unpkg](https://unpkg.com/veeno@0.0.1/dist/v-slider.min.js) version should support the script tag usage but I can't use it correctly.

Surely, there is `require(...)` in that script which is not interpreted by browser. So I guess we are back to the main question that I asked in the beginning  
###### how to exclude 3rd party plugin from building?

I tried to do it this way but nothing happened.

```
// rollup.config.js
import vue ---;
import buble ---;
import uglify ---;
import minimist ---;
import autoExternal from 'rollup-plugin-auto-external';  // added this plugin

const argv = ---;

const config = {
    input: ---,
    output: ---,
    plugins: [
        vue({
            ---
        }),
        autoExternal(),
        buble(),
    ],
};

---

export default config;
```
This is how I am using in .html file
```
<!DOCTYPE html>
    <html>
    <body>
      <div id="app">
        <veeno :handles="10" tooltips
        :range = "{ 'min': 100, 'max': 350 }"
        :pipsy = "{mode: 'range', density: 5}"
        ></veeno>
      </div>

      <script src="https://unpkg.com/vue/dist/vue.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/11.1.0/nouislider.js"></script>
      <script src="https://unpkg.com/veeno@0.0.1/dist/v-slider.min.js"></script>
      <script>
        new Vue({
          el: '#app'
        })
      </script>
    </body>
    </html>
```

**Comment by Lahori-Jawan** [comment]
okay! I figured it out and now its working. After this, I am feeling very confident in using bundlers and I owe this to you @mgdodge . Thank you. 

just in case someone is looking for how to remove the dependency. Here is my rollup config
```
// rollup.config.js
import vue from 'rollup-plugin-vue';
import buble from 'rollup-plugin-buble';
import uglify from 'rollup-plugin-uglify-es';
import minimist from 'minimist';

const argv = minimist(process.argv.slice(2));

const config = {
    input: 'src/index.js',
    output: {
        name: 'veeno',
        exports: 'named',
        globals: {                            // added
            noUiSlider: 'noUiSlider'
        }
    },
    external: ['nouislider'],          // added
    plugins: [
        vue({
            css: true,
            compileTemplate: true,
        }),
        buble(),
    ],
};

// Only minify browser (iife) version
if (argv.format === 'iife') {
    config.plugins.push(uglify());
}

export default config;
```

**Comment by mgdodge** [comment]
@Lahori-Jawan Glad you got it sorted out. Thanks for giving this utility a try!
