### ISSUE TITLE
TypeError: Cannot read property 'fd' of undefined

### ISSUE THREAD

**Issue by Torone** [team-innovation/vue-sfc-rollup#50]
Hello, I see this error when I try to use my new component.
It works fine in the original application but it looks bugged on the `.esm`

> TypeError: Cannot read property 'fd' of undefined
> at Function.useColors (my-test-lib.esm.js?9829:11415)

Looking on Google it looks a common issue with other libraries, but how can I fix it in mine?

I tried with some webpack configuration like `mainFields` and import the `.esm` file directly, but it doesn't help.

I'm using the component like this: `import { ComponentOne } from 'my-test-lib'`.

Thanks

**Comment by mgdodge** [comment]
This issue doesn't have enough information to even begin looking at things. Please provide a sample repo which reproduces the issue.
