### ISSUE TITLE
Problem with TypeScript declaration

### ISSUE THREAD

**Issue by EladEdri** [team-innovation/vue-sfc-rollup#54]
When building a library with v4.0.0-beta.0, the declaration uses `import { defineComponent, Plugin } from 'vue' `
Then, when importing this plugin in another Vue3 project (with TypeScript) - it causes a mismatch between Plugin (the way it's exported by runtime-core.d.ts) and the actual type inferred by TypeScript (which is Plugin_2)
Changing the plugin import from `Plugin` to `Plugin_2` solves the problem. 
I'm not sure whether it's an issue with vue-sfc-rollup or a bug in Vue-3.

**Comment by mgdodge** [comment]
Thanks for the repot - I'll look into that!

**Comment by mgdodge** [comment]
Just published 4.0.0-beta.1, which should address this issue. Please give it a try, let me know if it works for you.

**Comment by mgdodge** [comment]
Is this still an issue?

**Comment by EladEdri** [comment]
As of v4.0.5 it seems to be working fine.
