### ISSUE TITLE
Package TS interfaces under the a component namespace

### ISSUE THREAD

**Issue by belvederef** [team-innovation/vue-sfc-rollup#59]
Is there a way to include all the component interfaces under the component itself? So that I could import the component with:
```js
import { MyButtonComponent } from '@company/vue-component-library';
```
and use its related interfaces like so?
```js
myProp: MyButtonComponent.MyButtonPropInterface; // MyButtonPropInterface is the TS type describing the prop shape
```

I found you can import components and their interfaces just fine from `@company/vue-components` but I don't like this solution since it becomes a mess when you have 20 components and their interfaces all come under the same top namespace.

---
One thing that I thought could work is namespacing my library so you can import the components and their related interfaces like this:
```js
import MyButton, { MyButtonPropInterface, MyOtherInterface } from '@company/vue-component-library/my-button';
```
However, this introduces extra complexity, as I believe I need to produce multiple output files under the `/dist` folder (and the package.json needs to point to a single file, so not sure on how to solve that).

If you have any idea on how to solve this, please let me know.

**Comment by mgdodge** [comment]
This is not an issue about vue-sfc-rollup, but more a question about how to properly write typescript defs. Please limit issues to actual vue-sfc-rollup bugs.

It might be worth reading up on [barrel files](https://basarat.gitbook.io/typescript/main-1/barrel) for exporting multiple individual components from a single file. When using vue-sfc-rollup in library mode, this is what is created. The package.json file at that point still only points to a single output, but users of your library can import just the pieces they need.
