### ISSUE TITLE
Creating Universal Libraries for Vue 2 and 3

### ISSUE THREAD

**Issue by peoray** [team-innovation/vue-sfc-rollup#60]
I came across this plugin [vue-demi](https://github.com/antfu/vue-demi) that claims to create universal libraries for Vue 2 and 3 without having to maintain different branches. I haven't tried it but planning to for my next project.

Will this be compatible with the vue-sfc-rollup setup? Not sure how all of this works, hence the question. I want to know if it's possible to include the plugin in this current setup without breaking anything

**Comment by mgdodge** [comment]
I have seen this, and while at the outset it looks great, there is one downside. Use of vue-demi requires use of the composition api. This will make vue-sfc-rollup unusable for anyone who wishes to continue using the options api. As such, I don't think it will become part of the default output of this utility. It might be worth investigating it as an option to select during init, however.

That being said, I don't think there is anything that would prevent the use of vue-demi with the output of vue-sfc-rollup, if you choose to. As long as you are aware that you are passing a new dependency to your users, and will need to write your component/library with the composition api in mind, it should work fine.

**Comment by peoray** [comment]
Didn't know you had to use the composition API. Thanks for the detailed explanation :+1:
