### ISSUE TITLE
Async / Await does not work in unit tests

### ISSUE THREAD

**Issue by IvanSafonov** [team-innovation/vue-sfc-rollup#63]
I have created a new project with vue-sfc-rollup and added jest unit tests. And got this error:
```
 FAIL  tests/unit/example.spec.ts
  Async/Await
    ✕ encountered a declaration exception (3ms)

  ● Async/Await › encountered a declaration exception

    ReferenceError: regeneratorRuntime is not defined

      1 | describe("Async/Await", () => {
    > 2 |   it("check if it's working", async () => {
        |     ^
      3 |     expect("msg").toMatch("msg");
      4 |   });
      5 | });

      at Suite.<anonymous> (tests/unit/example.spec.ts:2:5)
      at Object.<anonymous> (tests/unit/example.spec.ts:1:1)

```

To reproduce,
```bash
# install latest version of the vue-sfc-rollup
npm i -g vue-sfc-rollup@4.0.0-beta.1

# create a new project with it
sfc-init
# ✔ Which version of Vue are you writing for? › Vue 3
# ✔ Is this a single component or a library? › Library
# ✔ What is the npm name of your library? … test-async
# ✔ Will this library be written in JavaScript or TypeScript? › TypeScript
# ✔ Enter a location to save the library files: … ./test-async

# add jest unit tests to the created project
cd ./test-async
vue add unit-jest
```
Change `./tests/unit/example.spec.ts` with this
```typescript
describe("Async/Await", () => {
  it("check if it's working", async () => {
    expect("msg").toMatch("msg");
  });
});
```
And run it
```bash
npm run test:unit
```

**Comment by IvanSafonov** [comment]
I replaced babel.config.js with the default vue cli preset and now it's working. But I'm not sure if it's a proper fix and it won't break anything else.

```javascript
// babel.config.js
module.exports = {
  presets: ["@vue/cli-plugin-babel/preset"]
};
```

**Comment by webistomin** [comment]
> I replaced babel.config.js with the default vue cli preset and now it's working. But I'm not sure if it's a proper fix and it won't break anything else.
> 
> ```js
> // babel.config.js
> module.exports = {
>   presets: ["@vue/cli-plugin-babel/preset"]
> };
> ```

Alternatively, you can do something like this

```js
module.exports = {
  presets: ['@babel/preset-env'],
  env: {
    test: {
      plugins: ['@babel/plugin-transform-runtime'],
    },
  },
}
```

**Comment by mgdodge** [comment]
vue-sfc-rollup does not produce unit tests (yes, I can hear the screams), so your repro is not truly as "vanilla" as it would seem. It sounds like you have a couple of working suggestions here. Since this is dealing with configuration outside the scope of the utility as it currently exists, I am closing this issue. Happy to investigate further if/when unit tests become a supported option out of the box.
