### ISSUE TITLE
Compatibility with vue-class-component

### ISSUE THREAD

**Issue by jackiems82** [team-innovation/vue-sfc-rollup#65]
Hi, I feel this might be the wrong spot to post this, but I think the knowledge of this tool might not be so widespread. So please apologize if this is misplaced. But maybe it is an issue with babel itself?

I would like to use this tool to configure an existing library that we created with Vue 2 using vue-class-component and corresponding syntax. With Vue 3 we would like to bring this to the next level and also have proper type exports as we did not have this so far.  We hope to leverage this tool for that matter.

What is currently not working is that I get an error on decorators like @Options. I tried to add `plugins: ["@babel/plugin-proposal-decorators", { "legacy": true }]` to the babel config, but still no luck. Does anyone here know how to make it build with vue-class-component for Vue3?

Any help would be highly appreciated.

**Comment by jackiems82** [comment]
OK, in the end I did manage to solve this with appropriate configuration in the babel config like so:

```
 plugins: [
        ['@babel/plugin-proposal-decorators', { "legacy": true }],
        '@babel/plugin-proposal-class-properties',
    ],
```

**Comment by tokidoki11** [comment]
I faced `(plugin babel) Error: Cannot find package '@babel/preset-plugin-proposal-decorators'`
I wonder why
