### ISSUE TITLE
Should the dist/ directory be committed to git?

### ISSUE THREAD

**Issue by jackdomleo7** [team-innovation/vue-sfc-rollup#66]
Hi, I was reading the documentation and was struggling to find any guidance on whether it's best practise to commit the `dist/` directory to git?

Awesome project by the way!!

**Comment by mgdodge** [comment]
That's a matter of personal preference, I've seen repos written both ways. NPM modules aren't typically installed directly from git, though, so there is no real need to. Anyone checking out your repo should, theoretically, be able to reproduce the dist directory by running the build script.

Closing, as this is a non-issue. Appreciate this, but please limit comments to actual issues.
