### ISSUE TITLE
Vite project errors

### ISSUE THREAD

**Issue by Aminerman** [team-innovation/vue-sfc-rollup#67]
Hello, thank you for this repository and the work you're doing on it.

I need your guidance about this. I'm trying to use my plugins, created using the existing rollup.config.js without any changes, in a Vite (Vue3) project and I'm getting these errors:
![image](https://user-images.githubusercontent.com/7825144/102787386-4ae13180-43a1-11eb-87f4-53dcfff6cc4d.png)

here is the overall structure of my `entry.js` : 
```javascript
/* eslint-disable */
import KinesisContainer from './components/kinesis-container.vue';

import * as components from './components/index';

const install = function (vue) {
  if (install.installed) {
    return;
  }
  install.installed = true;

  for (const name in components) {
    vue.use(components[name]);
  }

  vue.component('kinesis-container', KinesisContainer);
};

const Plugin = { install };

let GlobalVue = null;

if (typeof window !== 'undefined') {
  GlobalVue = window.vue;
} else if (typeof global !== 'undefined') {
  GlobalVue = global.vue;
}

if (GlobalVue) {
  GlobalVue.use(Plugin);
}

export default Plugin;

export {
  KinesisContainer
};
```

Do you have any clues about this?

**Comment by mgdodge** [comment]
A sample repo would be most helpful, but I suspect that there might be a couple things to look at. First is that Vue 3 cannot use Vue2 plugins/libraries natively, so you must recompile for Vue 3. Installing the current beta `vue-sfc-rollup@next` (hope to release final soon) you can scaffold out a config that is ready for Vue 3.

Second, the entry.js you have here is a little bit older style, which tries to access the global Vue. Vue 3 does not have a global vue instance (or at least doesn't install plugins on the global vue), again resolved by scaffolding out a config using the latest version.

I should note that when you scaffold a new config, most of the time you can copy your code directly in and things will compile/work with very little modification - from a packaging perspective. There might still be vue deprecations to worry about, but that is to be expected with major version changes like this.

There are community options to help while migrating from Vue 2 to Vue 3. [VueDemi](https://www.npmjs.com/package/vue-demi) seems pretty popular, and is aimed at helping to maintain both v2 and v3 at the same time. Alternatively, [vue-2-3](https://www.npmjs.com/package/vue-2-3) seems aimed at using one codebase in both version. I personally haven't used either yet, but they might be worth a look.

Closing this issue, though happy to re-open if you can provide a sample repo illustrating that the latest vue-sfc-rollup indeed produces bad output.

**Comment by Aminerman** [comment]
Hi again, 
Thank you for the thorough answer. I indeed managed to make it work with the `4.0.0-beta.1`. Thanks a bunch! This is amazing :)
