### ISSUE TITLE
Question: component props type definition

### ISSUE THREAD

**Issue by webistomin** [team-innovation/vue-sfc-rollup#69]
Hi! 

You are using ```export const Component: VueConstructor<Vue>;``` for component typings. Do I correctly understand that there is no way to add props type definition in Vue 2? 

I looked at how `Vuetify` did this. 
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/types/lib.d.ts#L17

It uses the same solution. Will it be enough for users?

Thanks.

**Comment by mgdodge** [comment]
This question is not something that directly affects how vue-sfc-rollup works, and as you indicated, the scaffolded code already matches some pretty well documented usage. Closing as a non-issue, though it is a good thing to research independently.
