### ISSUE TITLE
Could not resolve dependency for Vue2

### ISSUE THREAD

**Issue by tantee** [team-innovation/vue-sfc-rollup#70]
When running 'npm  install' after create project with vue2 option, there is a dependency error.

npm ERR! Could not resolve dependency:
npm ERR! peer vue@"3.0.5" from @vue/compiler-sfc@3.0.5
npm ERR! node_modules/@vue/compiler-sfc
npm ERR!   peerOptional @vue/compiler-sfc@"^3.0.0-beta.14" from @vue/cli-service@4.5.11
npm ERR!   node_modules/@vue/cli-service
npm ERR!     dev @vue/cli-service@"^4.5.10" from the root project
npm ERR!     1 more (@vue/cli-plugin-babel)

after explore to @vue/compiler-sfc@3.0.5, it require vue3 as its dependency.

update : I found that it did not show this error if npm is version 6. It seem that npm version 7 check for conflict peerDependencies

**Comment by mgdodge** [comment]
I've seen several packages in the npm ecosystem struggling with npm7. Unfortunately, this might be one of them, and it's a bug in an upstream dependency, not in vue-sfc-rollup code. The only way I can see to fix things is to set the @vue/cli-service dependency to an earlier version that doesn't try bringing in vue 3 - not sure which one, that would take a little research. I don't think we can really install vue 3 alongside vue 2 and resolve it ourselves - npm aliases would technically let us have them both installed, but one would have to be aliased, and I don't know if that would resolve things upstream. Might be worth looking at...

The best thing to do would be to log this bug with @vue/cli-service, as that is where the peer dependency is introduced. This particular issue could appear on any project that uses npm 7, vue 2, and recent versions of @vue/cli-service

**Comment by mgdodge** [comment]
Looks like it's already been reported: https://github.com/vuejs/vue-cli/issues/6270. The workaround is to run `npm i --legacy-peer-deps` instead when installing things.
