### ISSUE TITLE
There are so many warnings during installation.

### ISSUE THREAD

**Issue by OtabekSadiridinov** [team-innovation/vue-sfc-rollup#72]
### These warnings are being shown during installation. When I run npm install in the project.
I think the plugins used are old for now. I think they must be upgraded and this problem should be solved.

```bash
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
```

**Comment by mgdodge** [comment]
Running npm install from npm 6, the output is vastly different from npm 7 (which it seems you have here). In addition, none of these are direct dependencies. When updating all direct dependencies to their most recent versions, all of these warnings still appear. To get these resolved, the responsibility lies with those upstream dependencies requiring the deprecated packages.

If it's any comfort, these are deprecation notices only, not security warnings. There is no immediate harm in using them as they are. Most package maintainers are very good at addressing security related warnings.

Closing this issue, as there is nothing that can be done here - the changes need to be made upstream.
