### ISSUE TITLE
How can I configure Tailwind CSS with the pre-made library template

### ISSUE THREAD

**Issue by obadakhalili** [team-innovation/vue-sfc-rollup#73]
This is rather a questionnaire than an issue. How can I configure the template to start using Tailwind with my library?
Such that when I build the project, only Tailwind's used classes arrive to production builds.

**Comment by mgdodge** [comment]
I personally don't use tailwind for any of my work, so I would have no experience with this. The scaffolding set up is using the official vue rollup plugin, and doesn't really do anything fancy, so anything you find on the web about using tailwind with rollup would probably just work here with very little if any effort. I don't think this is the right avenue to ask this type of question, though.

Closing this as it is not an issue with this utility.
