### ISSUE TITLE
Ignore  Styles (CSS/SCSS)

### ISSUE THREAD

**Issue by areindl** [team-innovation/vue-sfc-rollup#74]
Hi Guys!
First a huge thank you! The vue-sfc-rollup was a tremendous help and it really allowed me scaffolding my UI library development. 

I am new to rollup and a question: I integrated a scss-bundle that now outputs a scss-file with all my styles. So in my consuming project I can integrate that. However, the css still gets extracted and is integrated in the esm-module as inline-style. How can I disable that and make the build-process simply ignore the styles? When I set `{css:false}` on the `vue-rollup-plugin`, I get babel-errors.

Any hint?

Thanks in advance and again, thank you!

**Comment by areindl** [comment]
Thanks to help from @weizhenye this was fixed:

Adding two plugins:

```js
import css from 'rollup-plugin-css-only'
import bundleScss from 'rollup-plugin-bundle-scss'
```

Then add it to the base config. You need to disable the css-processing for vue:

```js

const baseConfig = {
/* plugins... */
        vue: {
            css: false,
            template: {
                isProduction: true,
            },
        },
        bundleScss: {
            output: 'fuel.scss',
        },
        css: {
            output: false,
        },
```

Finally add the plugins to the rollup targets (eg. for es):
```js
const buildFormats = []
if (!argv.format || argv.format === 'es') {
    const esConfig = {
    /*** .... your config ***/

            plugins: [
            replace(baseConfig.plugins.replace),
            ...baseConfig.plugins.preVue,
            commonjs(),
            bundleScss({ ...baseConfig.plugins.bundleScss }),
            vue(baseConfig.plugins.vue),
            ...baseConfig.plugins.postVue,
            css({ ...baseConfig.plugins.css }),
            babel({
                ...baseConfig.plugins.babel,
                presets: [
                    [
                        '@babel/preset-env',
                        {
                            targets: esbrowserslist,
                        },
                    ],
                ],
            }),
        ],
```

It's important that bundleCss is called _before_ vue in the plugin array and that commonJs goes up.

Any comments on that solution?

**Comment by mgdodge** [comment]
v2.3.1 resolved a bug with optional chaining/nullish coalescing, and moving commonjs DOWN in the list was the resolution to that problem. You might want to try putting some test code in that uses optional chaining, just as a sanity check.

**Comment by mgdodge** [comment]
Since this was out of the scope of this utility (a custom configuration) and has been resolved elsewhere, I am closing this issue.
