### ISSUE TITLE
Can't compile .scss files.

### ISSUE THREAD

**Issue by otabekoff** [team-innovation/vue-sfc-rollup#79]
I created Vue3 Component library.

I installed these dependencies:
- "node-sass": "^5.0.0",
- "sass": "^1.32.8",
- "sass-loader": "^10.1.1"

I am using NPM.

Operating System: Windows_NT(10.0.19042) - win32/x64     
NodeJs: 14.15.3
npm: 6.14.9
yarn: 1.22.10

I created `vue.config.js` at the project folder and it is working.
I imported additional `variables.css`
And it is working when I run `npm run serve`. Namely, styles are working without any warning.

```js
// vue.config.js
module.exports = {
  css: {
    loaderOptions: {
      scss: {
        additionalData: `@import "~@/lib-global/variables.scss";`
      },
    }
  }
}
```

But when I want to run `npm run build`, it is giving a warning:
```bash
(!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
```

and this error:

```bash
[!] (plugin vue) Error: Undefined variable.
   ╷
10 │     color: $primary;
   │            ^^^^^^^^
   ╵
  src\lib-components\bek-sample.vue 10:12  root stylesheet
  ```
  
full error below:
```bash
[!] (plugin vue) Error: Undefined variable.
   ╷
10 │     color: $primary;
   │            ^^^^^^^^
   ╵
  src\lib-components\bek-sample.vue 10:12  root stylesheet
src\lib-components\bek-sample.vue?vue&type=style&index=0&id=97fc0a6a&lang.css
Error: Undefined variable.
   ╷
10 │     color: $primary;
   │            ^^^^^^^^
   ╵
  src\lib-components\bek-sample.vue 10:12  root stylesheet
    at error (V:\projects\uis\bek\node_modules\rollup\dist\shared\rollup.js:5285:30)
    at throwPluginError (V:\projects\uis\bek\node_modules\rollup\dist\shared\rollup.js:17941:12)
    at Object.error (V:\projects\uis\bek\node_modules\rollup\dist\shared\rollup.js:18548:24)
    at Object.error (V:\projects\uis\bek\node_modules\rollup\dist\shared\rollup.js:18110:38)
    at V:\projects\uis\bek\node_modules\rollup-plugin-vue\dist\style.js:51:56
    at Array.forEach (<anonymous>)
    at Object.transformStyle (V:\projects\uis\bek\node_modules\rollup-plugin-vue\dist\style.js:51:23)
    at ModuleLoader.addModuleSource (V:\projects\uis\bek\node_modules\rollup\dist\shared\rollup.js:18304:30)
    at ModuleLoader.fetchModule (V:\projects\uis\bek\node_modules\rollup\dist\shared\rollup.js:18360:9)
    at async Promise.all (index 2)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bek@1.0.0 build: `cross-env NODE_ENV=production rollup --config build/rollup.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bek@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Otabek Sadiridinov\AppData\Roaming\npm-cache\_logs\2021-03-11T11_08_15_369Z-debug.log
```

And also I tried to add ```import "./lib-global/variables.scss";`` in entry.js and entry.min.js after I tried above code.
And I get below error:

```bash
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
```

full error below

```bash
s the next major version will default this option to `true`.
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src\lib-global\variables.scss (1:10)
1: $primary: #ff0000;
             ^
2:
3: @import "styles";
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (V:\projects\uis\bek\node_modules\rollup\dist\shared\rollup.js:5285:30)
    at Module.error (V:\projects\uis\bek\node_modules\rollup\dist\shared\rollup.js:9677:16)
    at Module.tryParse (V:\projects\uis\bek\node_modules\rollup\dist\shared\rollup.js:10089:25)
    at Module.setSource (V:\projects\uis\bek\node_modules\rollup\dist\shared\rollup.js:9984:24)
    at ModuleLoader.addModuleSource (V:\projects\uis\bek\node_modules\rollup\dist\shared\rollup.js:18304:20)
    at ModuleLoader.fetchModule (V:\projects\uis\bek\node_modules\rollup\dist\shared\rollup.js:18360:9)
    at async Promise.all (index 1)
    at ModuleLoader.fetchStaticDependencies (V:\projects\uis\bek\node_modules\rollup\dist\shared\rollup.js:18385:34)
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (V:\projects\uis\bek\node_modules\rollup\dist\shared\rollup.js:18362:9)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bek@1.0.0 build: `cross-env NODE_ENV=production rollup --config build/rollup.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bek@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Otabek Sadiridinov\AppData\Roaming\npm-cache\_logs\2021-03-11T11_05_04_874Z-debug.log
```

Then, also, I tried to install ``vue-rollup-plugin-scss``

in package.json in devDependencies:
- "rollup-plugin-scss": "^2.6.1",

and in build/rollup.config.js I did these edits:
I added `scss()` at the end of all plugins: []
```js
import scss from 'rollup-plugin-scss'

................

const baseConfig = {
....................
    plugins:[
    ......................
                 scss()
                ]
}
```

But this didn't help. And giving this error:
```bash
[!] (plugin babel) SyntaxError: V:\projects\uis\bek\src\lib-components\bek-sample.vue?vue&type=style&index=0&id=97fc0a6a&lang.scss: Unexpected token (2:0)

  1 |
> 2 | .bek-sample {
    | ^
  3 |     display: block;
  4 |     width: 400px;
  5 |     margin: 25px auto;
src\lib-components\bek-sample.vue?vue&type=style&index=0&id=97fc0a6a&lang.scss (2:0)
SyntaxError: V:\projects\uis\bek\src\lib-components\bek-sample.vue?vue&type=style&index=0&id=97fc0a6a&lang.scss: Unexpected token (2:0)       

  1 |
> 2 | .bek-sample {
    | ^
  3 |     display: block;
  4 |     width: 400px;
  5 |     margin: 25px auto;
    at Parser._raise (V:\projects\uis\bek\node_modules\@babel\parser\src\parser\error.js:97:45)
    at Parser.raiseWithData (V:\projects\uis\bek\node_modules\@babel\parser\src\parser\error.js:92:17)
    at Parser.raise (V:\projects\uis\bek\node_modules\@babel\parser\src\parser\error.js:41:17)
    at Parser.unexpected (V:\projects\uis\bek\node_modules\@babel\parser\src\parser\util.js:161:16)
    at Parser.parseExprAtom (V:\projects\uis\bek\node_modules\@babel\parser\src\parser\expression.js:1208:20)
    at Parser.parseExprSubscripts (V:\projects\uis\bek\node_modules\@babel\parser\src\parser\expression.js:611:23)
    at Parser.parseUpdate (V:\projects\uis\bek\node_modules\@babel\parser\src\parser\expression.js:591:21)
    at Parser.parseMaybeUnary (V:\projects\uis\bek\node_modules\@babel\parser\src\parser\expression.js:558:23)
    at Parser.parseExprOps (V:\projects\uis\bek\node_modules\@babel\parser\src\parser\expression.js:366:23)
    at Parser.parseMaybeConditional (V:\projects\uis\bek\node_modules\@babel\parser\src\parser\expression.js:331:23)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bek@1.0.0 build: `cross-env NODE_ENV=production rollup --config build/rollup.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bek@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Otabek Sadiridinov\AppData\Roaming\npm-cache\_logs\2021-03-11T11_19_51_289Z-debug.log
```

Then I search for that errors and see that `preprocessStyles: true` was helping many people.
Then I look for the `vue:({})` part of my vue.rollup.config.js file.
And I see that it was referenced to a `baseConfig` variable at above it.
```js
vue(baseConfig.plugins.vue),
```
Then I see that it has a `vue part in plugins section`, but that was not a function because it was directly being referenced in that vue() function. I understand what's being here. I return to the code that it was  when the project is scaffolded for the first time. And write `preprocessStyles: true` in it and run `npm run build`.
And it didn't work for me.

Please help me to use SCSS in my project.

**Comment by otabekoff** [comment]
@mgdodge

**Comment by axtho** [comment]
Did you add this to rollup.config.js, under plugins?
```
vue: {
      preprocessStyles: true,
    },
```

**Comment by otabekoff** [comment]
Yes. I added that. I want three js files(min, esm, cjs) they are being generated.
But, I want the styles should be compiled in a file or two. For instance, **mylib.min.css** and **mylib.css**.

**Comment by axtho** [comment]
In my project I got it to work like that:

```
postcss({
        modules: true,
        extract: true,
        sourceMap: true,
        minimize: true,
      }),
```

**Comment by mgdodge** [comment]
Is this still an issue? I was wondering if this might have been suffering from the bug mentioned [here](https://github.com/team-innovation/vue-sfc-rollup/issues/83) which has since been resolved.

I typically don't extract my stylesheets, so I can't speak to that, and the scaffold output by this utility doesn't do that by default.

**Comment by SvenBudak** [comment]
Is there any solution for this problem? i just created a new lib with `sfc-init` and changed in the default example component `<style lang="scss" scoped>`... But when i try to build i get:

```
 INFO  Starting development server...
Starting type checking service...
Using 1 worker with 2048MB memory limit
98% after emitting

 ERROR  Failed to compile with 1 error                                                                                                                                                                                                         07:45:02

Failed to resolve loader: sass-loader
You may need to install it.
Type checking in progress...
No type errors found
Version: typescript 3.9.9
Time: 1995ms
```

**Comment by oebrab** [comment]
Try this:

```js
const baseConfig = {
  ...others,
  vue: {
    preprocessStyles: true,
  },
  postVue: [
    ...others,
    PostCSS(),
  ]
}
```

**Comment by otabekoff** [comment]
Thanks problem is solved!

**Comment by yungsilva** [comment]
@otabekoff  can you show how you solved it, how was your `rollup.config.js`?

tried everything above but it looks confused, where does `PostCSS()` come from?

**Comment by yungsilva** [comment]
> Try this:
> 
> ```js
> const baseConfig = {
>   ...others,
>   vue: {
>     preprocessStyles: true,
>   },
>   postVue: [
>     ...others,
>     PostCSS(),
>   ]
> }
> ```

@oebrab where does `PostCSS()` come from?

**Comment by oebrab** [comment]
> > Try this:
> > ```js
> > const baseConfig = {
> >   ...others,
> >   vue: {
> >     preprocessStyles: true,
> >   },
> >   postVue: [
> >     ...others,
> >     PostCSS(),
> >   ]
> > }
> > ```
> 
> @oebrab where does `PostCSS()` come from? are you using Vue 2 or 3?

`import PostCSS from "rollup-plugin-postcss";`, Vue 3

**Comment by Sweet-KK** [comment]
this still doesn't work

**Comment by fidalgodev** [comment]
Can't seem to make it work either....

my `vue.config.js`

```module.exports = {
  css: {
    loaderOptions: {
      sass: {
        additionalData: `@import "./src/tokens/generated/tokens.scss"; @import "./src/scss/mixins.scss";`,
      },
    },
  },
}
```

I can do `yarn dev` and serve my app/story book and it works fine. But when I do `yarn build`, which uses rollup, it says can't find the variables....

The only way I can make it build, is if I also import it on my `rollup.config.js` file

```plugins: [
    vue({
      css: false,
      preprocessStyles: true,
      preprocessOptions: {
        scss: vueConfig.css.loaderOptions.sass,
      },
    }),
```

Which is weird. Shouldn't I be able to just import it in the `vue.config.js` which allows me to use it withing the app and serve it, shouldn't roll up pick it up?

```
"rollup-plugin-vue": "^6.0.0",
 "rollup-plugin-postcss": "^4.0.0",
    "sass": "^1.26.5",
    "sass-loader": "^12.1.0",
```

**Comment by otabekoff** [comment]
Hi everyone. This issue was opened ages ago. And now I am closing this issue. Because, problem is resolved.
1. I created new project using **sfc-init**.
2. Then, ```yarn add sass```.
3. I created __src/lib-components/color.scss__
4. I imported it in __...-sample.vue__ like below.
```vue
<style lang="scss" scoped>
@import "./color.scss";
...................
</style>
```
5. added below code to fix warning. But not necessary.
```js
    replace: {
      preventAssignment: true,
      'process.env.NODE_ENV': JSON.stringify('production'),
    },
```
6. Added ```license.txt``` file to get rid of the license warning. Instead you can add ```private: true``` in package.json. But also this is not necessary to fix the scss issue too.
5. run ```yarn build```.

Then it worked!!!

**Comment by biennui1998mu** [comment]
You guys can try that change .css to .scss in include prop. 

``` javascript
postVue: [
      resolve({
        extensions: ['.js', '.jsx', '.ts', '.tsx', '.vue'],
      }),
      // Process only `<style module>` blocks.
      PostCSS({
        modules: {
          generateScopedName: '[local]___[hash:base64:5]',
        },
        include: /&module=.*\.scss$/,
      }),
      // Process all `<style>` blocks except `<style module>`.
      PostCSS({ include: /(?<!&module=.*)\.scss$/ }),
      commonjs(),
    ],
```

This work for me!

**Comment by otabekoff** [comment]
Sorry, I am back again because of not working again.
My setup:
```cmd
yarn: 1.22.18
npm: 8.5.0
OS: windows 11
Chrome: Latest general
    "sass": "^1.53.0",
    "sass-loader": "13.0.2",
    "@vue/cli-plugin-babel": "^4.5.13",
    "@vue/cli-service": "^4.5.13",
    "@vue/compiler-sfc": "^3.0.11",
    "rollup-plugin-vue": "^6.0.0",
    "vue": "^3.2.37",
    "vue-loader": "^16.8.3",
    "vue": "^3.0.5"
```

**Comment by otabekoff** [comment]
How about adding scss support officially instead of torturing us?

**Comment by otabekoff** [comment]
@mgdodge @SvenBudak @axtho @Sweet-KK @yungsilva @[biennui1998mu](https://github.com/biennui1998mu) @fidalgodev @oebrab @yungsilva Let's make a further discussion about this. I mentioned you all becuase you all know about this issue. We should solve this issue. This is happening since I open this issue. I really need help. Not only I am suffering from this bug, but others too. I've seen so many people posting this issue on stackoverflow, laracasts, other github repos and lots of other places. This became a big issue. Why shouldn't we get it fixed? Please be more responsible.

**Comment by SvenBudak** [comment]
> @mgdodge @SvenBudak @axtho @Sweet-KK @yungsilva @[biennui1998mu](https://github.com/biennui1998mu) @fidalgodev @oebrab @yungsilva Let's make a further discussion about this. I mentioned you all becuase you all know about this issue. We should solve this issue. This is happening since I open this issue. I really need help. Not only I am suffering from this bug, but others too. I've seen so many people posting this issue on stackoverflow, laracasts, other github repos and lots of other places. This became a big issue. Why shouldn't we get it fixed? Please be more responsible.

I'm very sorry to say this, but because of this problem i went back to angular. i thought for a small project, i should go with something more lightweight than angular. but i kept running into problems that angular already solves out of the box. since i don't have the time, i just decided to switch back to angular.

**Comment by mgdodge** [comment]
The decision has been made to deprecate `vue-sfc-rollup` in favor of better tooling in the Vue ecosyste, specifically the [vite "library build"](https://vitejs.dev/guide/build.html#library-mode) configuration. It is an excellent project, which is capable of everything vue-sfc-rollup strived to accomplish, and more.
