### ISSUE TITLE
How to bundle dynamic imports?

### ISSUE THREAD

**Issue by axtho** [team-innovation/vue-sfc-rollup#81]
This is more of a howto, then a bug issue.

I am working on a rewrite of a vue 2 WYSIWYG editor. The editor has different "modules", which are basically the buttons and their related logic (e.g. B, I, etc.). I resolved to load these dynamically, so that I don't need to bundle every possible module.

In dev mode this is fine, but after building the import of the bundle results in this error:

```
ERROR  Failed to compile with 1 errors                                                                                                                                      
This dependency was not found:
* @/modules in /Applications/MAMP/htdocs/hack/vue-editr/dist/vue-editr.ssr.js
To install it, you can run: npm install --save @/modules
```
My guess is that it cannot handle the dynamic imports [here](https://github.com/digitaldeacon/vue-editr/blob/master/src/composables/useLoadModules.ts).

I do not see the modules included in the final build. How do I get that working using your setup?
Obviously, I am new to working on npm publishable SFC files. 

The repo can be found here: https://github.com/digitaldeacon/vue-editr/.

**Comment by mgdodge** [comment]
This is beyond the scope of this utility, so I'm going to have to close this. You might find more helpful information [in this bug report](https://github.com/rollup/rollup/issues/2463) and its comments - it seems to be the same type of situation you are looking at.

Though it might not be the way you are using them here, my inclination for on-demand usage of optional features would be to export all the dynamic imports as separate, named exports of this library. Users could then import the ones they need, and pass them as options to the `Vue.use` or `app.use` (if Vue 3) command to "register" those with the plugin. This lets the user decide what to use by allowing them to inject only the pieces needed at the time of install.
