### ISSUE TITLE
@rollup/plugin-commonjs before @rollup/plugin-babel

### ISSUE THREAD

**Issue by nlien** [team-innovation/vue-sfc-rollup#82]
Hi! According to the [@rollup/plugin-babel doc](https://www.npmjs.com/package/@rollup/plugin-babel), the order of the plugins matter, if you are using the commonjs plugin alongside the babel plugin:

> When using @rollup/plugin-babel with @rollup/plugin-commonjs in the same Rollup configuration, it's important to note that @rollup/plugin-commonjs must be placed before this plugin in the plugins array for the two to work together properly

When inspecting the output from this utility, the commonjs plugin is placed *after* the babel plugin in the plugins array.

**Comment by mgdodge** [comment]
Will be resolved in next release.

**Comment by mgdodge** [comment]
This is fixed with v4.0.5, closing.
