### ISSUE TITLE
BABEL Cannot find module 'core-js/package.json'

### ISSUE THREAD

**Issue by SuuSoJeat** [team-innovation/vue-sfc-rollup#84]
>  INFO  Starting development server...
> 98% after emitting
> 
>  ERROR  Failed to compile with 1 error                                                                                                                                                                 7:43:22 AM
> 
>  error  in ./dev/serve.js
> 
> Syntax Error: Error: [BABEL] /Users/eterna/repo/caldera-calendar/dev/serve.js: Cannot find module 'core-js/package.json'
> Require stack:
> - /Users/eterna/repo/caldera-calendar/node_modules/@vue/babel-preset-app/index.js
> - /Users/eterna/repo/caldera-calendar/node_modules/@babel/core/lib/config/files/module-types.js
> - /Users/eterna/repo/caldera-calendar/node_modules/@babel/core/lib/config/files/configuration.js
> - /Users/eterna/repo/caldera-calendar/node_modules/@babel/core/lib/config/files/index.js
> - /Users/eterna/repo/caldera-calendar/node_modules/@babel/core/lib/index.js
> - /Users/eterna/repo/caldera-calendar/node_modules/@vue/cli-plugin-babel/index.js
> - /Users/eterna/repo/caldera-calendar/node_modules/@vue/cli-service/lib/Service.js
> - /Users/eterna/repo/caldera-calendar/node_modules/@vue/cli-service/bin/vue-cli-service.js (While processing: "/Users/eterna/repo/caldera-calendar/node_modules/@vue/babel-preset-app/index.js")
>     at Generator.next (<anonymous>)
>     at Generator.next (<anonymous>)
>     at Generator.next (<anonymous>)
> 
> 
>  @ multi (webpack)-dev-server/client?http://192.168.1.5:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./dev/serve.js
> 

It was a freshly generated project. I tried with other variations including Vue 3 and TypeScript.

**Comment by mgdodge** [comment]
This is a problem coming in from an upstream dependency - there is no direct dependency on core-js or it's package.json file. If you look at your own package.json file, you will see something like the following: `"@vue/cli-service": "^4.5.10"` - the error posted above seems to indicate that is the start of the dependency branch where the error is manifesting. Try removing the `^` from the version number to install an exact specific version. If that works, then you can try updating the version number incrementally until you find the point at which things break down.

None of this is guaranteed to work, it's just poking and prodding to find out when the breakage was introduced. Unfortunately, there's nothing that changed here which would cause this problem, as I've got several components which were generated this way, and none of them experience the issue you've highlighted here.

**Comment by SuuSoJeat** [comment]
I have tried your suggestion.

Removing the `^` doesn't work. I went on to try updating the version number decremental anyway but no luck. 

I also went a step further and reinstalled @vue/cli. I believe the cause to be something else.

**Comment by mgdodge** [comment]
Can you post a sample repo? I am running a fresh copy and have no issues at all.

**Comment by SuuSoJeat** [comment]
[Repo Link](https://github.com/SuuSoJeat/sample-bugfix-caldera)

I also include the node_modules for you.

**Comment by oebrab** [comment]
Try yarn instead of npm

**Comment by SuuSoJeat** [comment]
Yarn works perfectly. Thanks!

**Comment by mgdodge** [comment]
Closing this as it is an upstream issue. The code scaffolded is identical whether you use yarn or not. Problem lies elsewhere.
