### ISSUE TITLE
Error (babel) on npm run serve

### ISSUE THREAD

**Issue by Woosy** [team-innovation/vue-sfc-rollup#86]
Hello ! I've been trying to create a vue sfc using vue-sfc-rollup, however `npm run serve` doesn't seem to work (I haven't done any modification to the default files).

What I did:
- npm install -g vue-sfc-rollup
- sfc-init (vue2, single-component, javascript)
- cd my-project
- npm install
- npm run serve

And I got the following error message: 
![image](https://user-images.githubusercontent.com/26418696/114199150-58242b00-9954-11eb-897d-824d783de2c6.png)

I'm using node v14.16.0 (installed with nvm) on a MacBook Pro (intel).

**Comment by mgdodge** [comment]
Running the same command, I don't have the same issue. Even ran `npm install --cache /tmp/empty-folder` to ensure I wasn't getting cached npm modules.

If you try again, perhaps with the same cache technique I mentioend, does it still happen? If so, a sample repo that includes the generated package-lock.json might be helpful.

In all honesty, though, the error is not with the scaffolded code, it's an upstream error. So it's not something that can/needs to be fixed here.

**Comment by Plumpsssack** [comment]
Hello, I had the same error and 3 vulnerabilities. After fixing these by running "npm audit fix --force" everything worked fine.

**Comment by mgdodge** [comment]
Closing, as this is an upstream problem.

**Comment by xon52** [comment]
I appreciate this is maybe an upstream error but I find it odd using provided versions it is happening. I have the same error using scaffolded code, but forcing a dependency update makes a new error.

```bash
 ERROR  Failed to compile with 1 error                                                                                                                                                      11:30:54 pm
 error  in ./dev/serve.ts

Syntax Error: Error: [BABEL] D:\Projects\test\dev\serve.ts: Cannot find module 'core-js/package.json'
Require stack:
- D:\Projects\test\node_modules\@vue\babel-preset-app\index.js
- D:\Projects\test\node_modules\@babel\core\lib\config\files\module-types.js
- D:\Projects\test\node_modules\@babel\core\lib\config\files\configuration.js
- D:\Projects\test\node_modules\@babel\core\lib\config\files\index.js
- D:\Projects\test\node_modules\@babel\core\lib\index.js
- D:\Projects\test\node_modules\@vue\cli-plugin-babel\index.js
- D:\Projects\test\node_modules\@vue\cli-service\lib\Service.js
- D:\Projects\test\node_modules\@vue\cli-service\bin\vue-cli-service.js (While processing: "D:\\\\Projects\\test\\node_modules\\@vue\\babel-preset-app\\index.js")
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)


 @ multi (webpack)-dev-server/client?http://192.168.0.4:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./dev/serve.ts
```

**Comment by spnc-omz** [comment]
After strictly declaring which core npm package to include in my package.json my errors went away. Something was causing a weird collision. 

Try installing vue cli tools globally, vue upgrade, then if that still doesn't jive, add core-js and core-js-compat as dev dependencies. 

https://cli.vuejs.org/guide/installation.html
https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/babel-preset-app/package.json#L38-L39 

Hope that helps!
