### ISSUE TITLE
cannot use component in another project

### ISSUE THREAD

**Issue by KnowsCount** [team-innovation/vue-sfc-rollup#89]
thanks for this most extraordinary tool! I created a component library using `vue-sfc-rollup`, however, I met a problem when using a component in another project. details are in the link below:

https://github.com/KnowsCount/vue-lib/issues/3

This might be a problem caused by me, just checking if it's anything related to `vue-sfc-rollup`...

**Comment by mgdodge** [comment]
Did you try loading a Vue 2 component into a Vue 3 app? In Vue 2, components are registered with `Vue.component` where in Vue 3 they are registered with `app.component` - that would match the description. Vue-sfc-rollup gives you the option of writing for either Vue 2 or Vue 3, make sure you know your target.

**Comment by KnowsCount** [comment]
no... this is my package.json in my sample project using the component.

```
{
	"name": "example",
	"version": "0.1.0",
	"private": true,
	"scripts": {
		"serve": "vue-cli-service serve",
		"build": "vue-cli-service build"
	},
	"dependencies": {
		"@knowscount/vue-lib": "^1.1.4",
		"core-js": "^3.6.5",
		"vue": "^2.6.11"
	},
	"devDependencies": {
		"@vue/cli-plugin-babel": "~4.5.0",
		"@vue/cli-service": "~4.5.0",
		"vue-template-compiler": "^2.6.11"
	}
}
```

**Comment by mgdodge** [comment]
Looking at your source repo, it looks as if you created a library instead of a single component. Perhaps this will clarify the difference.

If you scaffold a single component, you can use it two ways:

```js
// Option 1: Register globally
import MyComponent from '@knowscount/my-component';

// Traditional vue component
Vue.component('MyComponent', MyComponent);
// Also supported when scaffolded via vue-sfc-rollup
Vue.use(MyComponent);
```
```js
// Option 2: Register locally
import MyComponent from '@knowscount/my-component';

export default {
  name: 'SomeParentComponent',
  components: {
    MyComponent,
  }
  ...
}
```

If you are writing a library of components, however, you must choose to import the entire library, or use a slightly different syntax to import individual components:

```js
// Import and register entire library
import MyLibrary from '@knowscount/my-library';
Vue.use(MyLibrary);
```
```js
// Import and register globally individual components from the library
import { MyComponent, MyComponent2 } from '@knowscount/my-library';
Vue.component('MyComponent', MyComponent);
Vue.component('MyComponent2', MyComponent2);
```
```js
// Import and register locally individual components from the library
import { MyComponent, MyComponent2 } from '@knowscount/my-library';

export default {
  name: 'SomeParentComponent',
  components: {
    MyComponent,
    MyComponent2,
  }
  ...
}
```

The sample you provided is a *library* which currently contains a single component. I tested it, and everything works if you follow any of the library example listed.

Closing this as issue, code produced by vue-sfc-rollup is fine.

**Comment by KnowsCount** [comment]
thanks!
