### ISSUE TITLE
How can I use  this with components created with vue/cli 3

### ISSUE THREAD

**Issue by skayablars** [team-innovation/vue-sfc-rollup#9]
Hello,

I'm trying to create a component library with vue cli 3. How can I integrate this tool to the existing project, I init one project but it seems it create a basic vue implementation. If I already have the components created with vue create library how can I integrate this tool to create my library?

**Comment by mgdodge** [comment]
Honestly, the fastest way would be to use vue-sfc-rollup itself to scaffold a new project structure, then copy your existing components into the '_lib-components/src_' directory created. Don't forget to update '_lib-components/src/index.js_' with an entry for each component in your library.

Alternatively, you could utilize this tool within an existing project manually by looking at the '_templates/library_' folder. The important bits are all in there, and there are only 5 files which you need to be concerned with.

- **_library-package.json_**: the dependencies and build scripts required for rollup to compile your library
- **_build/rollup.config.js_**: the actual rollup config file - you will need to name the library here, as well as update the path to the '_input_' file
- **_src/entry.js_**: the '_input_' file, which is likely to be used as-is
- **_src/lib-components/index.js_**: collect the components which are exported as part of your library here
- (optional) **_src/lib-dev.vue_**: a non-exported component, provided for use during development - use vue cli 3 to serve this one with hot-reloading, etc. while writing the actual library components

If you look at those files, all are very small and you should be able to use them to get what you need.

In either case, you end up letting vue-sfc-rollup do the actual bundling, but use vue cli 3 to do the actual development.
