### ISSUE TITLE
typescript vue library generated duplicated vue runtime

### ISSUE THREAD

**Issue by jaslioin** [team-innovation/vue-sfc-rollup#94]
context:
I use `npx vue-sfc-rollup` to create a vue component library, after building it and importing into  my vue app, i see the bundle analytics show 2 `vue.runtime.esm.js`, one is from my vue app, one is from the library

expect:
vue app bundle only one vue runtime

actual:
bundle has 2 vun runtime
![image](https://user-images.githubusercontent.com/15674058/117524223-38356500-afef-11eb-91b1-8003ad080a0a.png)
additional info:
- when i remove `import Vue from 'vue'` in one of the library sfc used for typing (`Vue.extend({})`), the duplicated vue runtime is gone, but lead to another runtime  error of `vue not found`

**Comment by mgdodge** [comment]
What are you using to generate that graph? I'd like to look further into this...

**Comment by jaslioin** [comment]
> What are you using to generate that graph? I'd like to look further into this...and a sample repo would be helpful.

Hi,
1. I used the vue-cli tool `vue ui`
2. Here's the repo containing both component library and a basic vue app using it. https://github.com/jaslioin/test-lerna

**Comment by pareshchouhan** [comment]
I am facing the exact same issue. so 👍

**Comment by pareshchouhan** [comment]
Ideally I would not want a runtime to be bundled with the library.

**Comment by mgdodge** [comment]
I haven't yet taken a deep dive into this, but I have never seen this behavior in normal usage at all. In fact, the rollup configuration generated by default specifically exludes vue itself from compilation. That code ca be found in the rollup.config.js file [here](https://github.com/team-innovation/vue-sfc-rollup/blob/6a95b5eca25e1d3f225b464d3a8d0b2f10f26b82/templates/library/build/rollup.config.js#L79), and it is included for this exact reason.

In glancing at your sample repo, it looks like you are installing the package via `npm install ../<relative-path-to-lib>` - as evidenced by [this line of the app package.json file](https://github.com/jaslioin/test-lerna/blob/518f79c54ffefb235623e2496fe6fed1b0a49356/packages/vue-app-one/package.json#L11). It is a known webpack issue that installing things this way (and also when installing via `npm link`) will cause webpack to resolve the library dependencies differently. [See this bug report](https://github.com/team-innovation/vue-sfc-rollup/issues/96) and specifically the last comment for details.

As an exercise, please try running `npm run build` to build your library as normal. The output files should be very small, and should not include vue itself. Then, run `npm pack` which creates a tarball of the files - this is actually what happens behind the scenes when you publish an npm library. Finally, install the library in a consuming app by running `npm install <the-generated-tarball.tgz>` which is what a typical npm install does. Everything should still work, but there will be no chance of webpack resolving the library dependencies the wrong way.

**Comment by pareshchouhan** [comment]
My bad, I did some  changes to package json to build for both vue2 and vue3 at the same time, my global (external) package was called vue-next in package.json. Changing these worked out :) sorry for the trouble. @mgdodge 

`// ESM/UMD/IIFE shared settings: externals
// Refer to https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
const external = [
  // list external dependencies, exactly the way it is written in the import statement.
  // eg. 'jquery'
  'vue-next'
];
// UMD/IIFE shared settings: output.globals
// Refer to https://rollupjs.org/guide/en#output-globals for details
const globals = {
  // Provide global variable names to replace your external imports
  // eg. jquery: '$'
  'vue-next': 'Vue'
};`
